[[redirects]]
  from = "/api/*"
  to = "https://team-wagu-prod.com/:splat"
  status = 200

[build]
  publish = "dist"
  command = "CI= npm run build:prod"

[context.develop]
  command = "CI= npm run build:dev"

[context.production]
  command = "CI= npm run build:prod"

[context.test]
  command = "CI= npm run build:test"