[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  /api/*  https://team-wagu-prod.com/:splat  200

[build]
  publish = "dist"
  command = "CI= npm run build:prod"

[context.develop]
  command = "CI= npm run build:dev"

[context.production]
  command = "CI= npm run build:prod"