[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"

[context.develop]
  command = "CI= npm run build:dev"

[context.production]
  command = "CI= npm run build:prod"