/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        dark: {
          primary: "#FFEB60",
          secondary: "#FBFBFB",
          tertiary: "#171717",
          danger: "#F5511D",
          cancel: "#6F6F6F",
          success: "#6AB6F0",
          error: "#FF784D",
          placeholder: "#8B8B8B",
          focus: "#81BFEF",
          white: "#FFFFFF",
          gray1: "#FBFBFB",
          gray3: "#F5F4F3",
          gray5: "#ECECEC",
          gray6: "#DFDFDF",
          gray7: "#C1C1C1",
          gray8: "#A5A5A5",
          gray9: "#8B8B8B",
          gray10: "#6F6F6F",
          gray11: "#555555",
          gray12: "#3D3D3D",
          gray13: "#333333",
          gray14: "#242424",
          gray15: "#171717",
        },
      },
      fontFamily: {
        sans: ["Pretendard", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        title: ["2rem", "2.8rem"],
        subtitle: ["1.6rem", "2.4rem"],
        body: ["1.4rem", "2.2rem"],
        button: ["1.6rem", "2rem"],
        caption: ["1.2rem", "1.6rem"],
        d1: ["4rem", "4.8rem"],
        d2: ["3.2rem", "4.0rem"],
        d3: ["2.8rem", "3.6rem"],
        d4: ["2.4rem", "3.2rem"],
        d5: ["2rem", "2.8rem"],
      },
      fontWeight: {
        regular: 400,
        medium: 500,
        bold: 700,
      },
    },
  },
  plugins: [],
};
